---
title: 02 | LINEAR EQUATIONS
author:
    name: Dr Juan H Klopper
    affiliation: The George Washington University
title-block-banner: true
callout-icon: false
format: 
    html:
        toc: true
        toc-depth: 3
        toc-title: Content of this document
        toc-location: left
        number-sections: true
        embed-resources: true
        self-contained-math: true
        code-copy: true
        code-line-numbers: true
        code-link: true
        html-math-method: katex
        theme: sandstone
    pdf:
        toc: true
        toc-depth: 3
        toc-title: Content of this documents
---

## Introduction

In this notebook, we study linear equations. We find linear equations throughout nature. In public health and biomedical research, we often rely on models. The most commonly use model is a linear model, called linear regression. A linear regression model is a linear equation.

## Single variable linear equations

An equation in a single variable, $x$, is a __linear equation__ when it can be written as @eq-one, where $a$ and $b$ are constants, called __coefficients__, and $a \ne 0$. @eq-one is termed the __standard form__ of a single variable linear equation.

$$
ax = b
$$ {#eq-one}

We see an example of a single variable linear equation in @eq-ex1, where $n$ is the variable.

$$
3 \left( n - 1 \right) = 6
$$ {#eq-ex1}

We need a strategy to transform @eq-ex1 into the standard form, shown in @eq-one.

## Linear equations in two variables

we learn more about linear equations in two variables, $x$ and $y$. The generic form of such an equation is shown in @eq-linear.

$$
ax + by = c
$$ {#eq-linear}

In @eq-linear, $a$, $b$, and $c$ are constants and can be eany real number. They are termed __coefficients__. If we want to solve for $y$, then $b \ne 0$. We solve for $y$ in @eq-solvey.

$$
\begin{align}
&ax + (-ax) + by = c + (-ax) \\ \\ 
&by = c - ax \\ \\ 
&\left( \frac{1}{b} \right)by = \left( \frac{1}{b} \right) \left( c-ax \right) \\ \\ 
&y = \frac{c}{b} - \frac{a}{b}x
\end{align}
$$ {#eq-solvey}

The function in @eq-linear is linear since each of the variables are not raised to any power (except $1$), are not involved in multiplication or division of each other, and not part of any transofrmations such as square roots, logarithms, exponents, and so on.

